-- MySQL Script generated by MySQL Workbench
-- 04/20/20 15:21:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Timobank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Timobank` DEFAULT CHARACTER SET utf8 ;
USE `Timobank` ;

-- -----------------------------------------------------
-- Table `Timobank`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Timobank`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `passId` VARCHAR(45) NOT NULL,
  `balance` FLOAT NOT NULL DEFAULT 0,
  `pincode` VARCHAR(4) NOT NULL,
  `failedAttempts` INT NOT NULL DEFAULT 0,
  `isBlocked` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

-- ----------------------------
--  Records of `accounts`
-- ----------------------------
INSERT INTO accounts (name, passId, balance, pincode) VALUES 
("Daniël van der Drift", 1234567890, 80, "1234"),
("Zoë Zegers", 8467284987, 100, "1234"),
("Timo van der Meer", 0472786524, 120, "1234"),
("Robin Koot", 7236450982, 140, "1234"),
("Jantje", 2398475098, 50, "1234");


-- -----------------------------------------------------
-- Table `Timobank`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Timobank`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accounts_id` INT NOT NULL,
  `pinned_at_country` VARCHAR(45) NOT NULL DEFAULT 'US',
  `pinned_at_bank` VARCHAR(45) NOT NULL DEFAULT 'Timo-Bank',
  `balance_change` FLOAT NOT NULL,
  `is_positive` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_logs_accounts_idx` (`accounts_id` ASC),
  CONSTRAINT `fk_logs_accounts`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `Timobank`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
